# For more information about tox, see https://tox.readthedocs.io/en/latest/
[tox]
envlist = py{311,312,313}-{linux,macos,windows}
isolated_build=true

[gh-actions]
python =
    3.11: py311
    3.12: py312
    3.13: py313

[gh-actions:env]
PLATFORM =
    ubuntu-latest: linux
    macos-latest: macos
    windows-latest: windows

[testenv]
platform =
    macos: darwin
    linux: linux
    windows: win32
passenv =
    CI
    GITHUB_ACTIONS
    DISPLAY
    XAUTHORITY
    NUMPY_EXPERIMENTAL_ARRAY_FUNCTION
    PYVISTA_OFF_SCREEN
dependency_groups =
    dev
commands =
    linux,windows: pytest tests notebooks --color=yes --cov=muvis_align --cov-branch --cov-report=term-missing --nbmake \
                    --ignore notebooks/feature_matching_overlay.ipynb \
                    --ignore notebooks/feature_matching.ipynb
    macos: pytest tests notebooks --color=yes --cov=muvis_align --cov-branch --cov-report=term-missing --nbmake \
           --ignore notebooks/feature_matching_overlay.ipynb \
           --ignore notebooks/feature_matching.ipynb \
           --ignore notebooks/tile_staging_napari.ipynb

;commands = pytest tests\test_napari_interface_registration.py -v
